name: Copyright Checks

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths-ignore:
      - .github/**
      - .goreleaser.yml

jobs:
  go_generate:
    name: add headers check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: go install github.com/hashicorp/copywrite@latest
      - run: copywrite headers
      - name: Check for Git Differences
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after adding copyright headers. Run 'copywrite headers' command and commit."; exit 1)
